AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Helping customers break down data silos with AWS Integration services
  
Parameters:
  S3BucketName:
    Description: The S3 bucket name  where data is stored.
    Type: String
  S3BucketPrefix:
    Description: The S3 bucket Prefix where data is stored.    
    Type: String
  S3InputFormatConfig:
    Description: File Format for objects in S3 (CSV, JSON, PARQUET).
    Default: "JSON"
    Type: String    
  IntermediateBucketName:
    Description: Intermediate S3 Bucket Name, used by AppFlow to load data into Redshift.
    Type: String    
  PushFlowName:
    Description: The name of the  Flow to push data from Redshift
    Type: String
  PushFlowConnectorName:
    Description: The name of the desitnation connector
    Type: String
Resources:       
 
  AppFlowPushDefinition:
    Type: AWS::AppFlow::Flow
    Properties:
      FlowName:
        Ref: PushFlowName
      TriggerConfig:
        TriggerType: OnDemand
      SourceFlowConfig:
        ConnectorType: S3
        SourceConnectorProperties:
          S3:
            BucketName: !Ref S3BucketName
            BucketPrefix: !Ref S3BucketPrefix
            S3InputFormatConfig:
              S3InputFileType: !Ref S3InputFormatConfig

      DestinationFlowConfigList:
      - ConnectorProfileName:
          Ref: PushFlowConnectorName
        ConnectorType: Redshift
        DestinationConnectorProperties:
          Redshift:
            IntermediateBucketName: !Ref IntermediateBucketName
            Object: public.orders
      Tasks:
      - ConnectorOperator:
          S3: PROJECTION
        SourceFields:
        - SalesOrder
        - SalesOrderType
        - SalesOrganization
        - DistributionChannel
        - OrganizationDivision
        - SalesGroup
        - SalesOffice
        - SalesDistrict
        - SoldToParty
        - CreationDate
        - CreatedByUser
        - LastChangeDate
        - LastChangeDateTime
        - PurchaseOrderByCustomer
        - CustomerPurchaseOrderType
        - CustomerPurchaseOrderDate
        - SalesOrderDate
        - TotalNetAmount
        - TransactionCurrency
        - SDDocumentReason
        - PricingDate
        - RequestedDeliveryDate
        - ShippingCondition
        - CompleteDeliveryIsDefined
        - ShippingType
        - HeaderBillingBlockReason
        - DeliveryBlockReason
        - IncotermsClassification
        - IncotermsTransferLocation
        - IncotermsLocation1
        - IncotermsLocation2
        - IncotermsVersion
        - CustomerPaymentTerms
        - PaymentMethod
        - AssignmentReference
        - ReferenceSDDocument
        - ReferenceSDDocumentCategory
        - CustomerTaxClassification1
        - TaxDepartureCountry
        - VATRegistrationCountry
        - SalesOrderApprovalReason
        - SalesDocApprovalStatus
        - OverallSDProcessStatus
        - TotalCreditCheckStatus
        - OverallTotalDeliveryStatus
        - OverallSDDocumentRejectionSts
        TaskType: Filter
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: salesorder
        SourceFields:
        - SalesOrder
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: integer
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: salesordertype
        SourceFields:
        - SalesOrderType
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: salesorganization
        SourceFields:
        - SalesOrganization
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: integer
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: distributionchannel
        SourceFields:
        - DistributionChannel
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: integer
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: organizationdivision
        SourceFields:
        - OrganizationDivision
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: integer
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: salesgroup
        SourceFields:
        - SalesGroup
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: salesoffice
        SourceFields:
        - SalesOffice
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: salesdistrict
        SourceFields:
        - SalesDistrict
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: soldtoparty
        SourceFields:
        - SoldToParty
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: integer
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: creationdate
        SourceFields:
        - CreationDate
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: createdbyuser
        SourceFields:
        - CreatedByUser
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: lastchangedate
        SourceFields:
        - LastChangeDate
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: lastchangedatetime
        SourceFields:
        - LastChangeDateTime
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: purchaseorderbycustomer
        SourceFields:
        - PurchaseOrderByCustomer
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: customerpurchaseordertype
        SourceFields:
        - CustomerPurchaseOrderType
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: customerpurchaseorderdate
        SourceFields:
        - CustomerPurchaseOrderDate
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: salesorderdate
        SourceFields:
        - SalesOrderDate
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: totalnetamount
        SourceFields:
        - TotalNetAmount
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: numeric
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: transactioncurrency
        SourceFields:
        - TransactionCurrency
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: sddocumentreason
        SourceFields:
        - SDDocumentReason
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: pricingdate
        SourceFields:
        - PricingDate
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: requesteddeliverydate
        SourceFields:
        - RequestedDeliveryDate
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: shippingcondition
        SourceFields:
        - ShippingCondition
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: integer
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: completedeliveryisdefined
        SourceFields:
        - CompleteDeliveryIsDefined
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: shippingtype
        SourceFields:
        - ShippingType
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: headerbillingblockreason
        SourceFields:
        - HeaderBillingBlockReason
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: deliveryblockreason
        SourceFields:
        - DeliveryBlockReason
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: incotermsclassification
        SourceFields:
        - IncotermsClassification
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: incotermstransferlocation
        SourceFields:
        - IncotermsTransferLocation
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: incotermslocation1
        SourceFields:
        - IncotermsLocation1
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: incotermslocation2
        SourceFields:
        - IncotermsLocation2
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: incotermsversion
        SourceFields:
        - IncotermsVersion
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: customerpaymentterms
        SourceFields:
        - CustomerPaymentTerms
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: integer
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: paymentmethod
        SourceFields:
        - PaymentMethod
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: assignmentreference
        SourceFields:
        - AssignmentReference
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: referencesddocument
        SourceFields:
        - ReferenceSDDocument
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: referencesddocumentcategory
        SourceFields:
        - ReferenceSDDocumentCategory
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: customertaxclassification1
        SourceFields:
        - CustomerTaxClassification1
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: taxdeparturecountry
        SourceFields:
        - TaxDepartureCountry
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: vatregistrationcountry
        SourceFields:
        - VATRegistrationCountry
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: salesorderapprovalreason
        SourceFields:
        - SalesOrderApprovalReason
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: salesdocapprovalstatus
        SourceFields:
        - SalesDocApprovalStatus
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: overallsdprocessstatus
        SourceFields:
        - OverallSDProcessStatus
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: totalcreditcheckstatus
        SourceFields:
        - TotalCreditCheckStatus
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: overalltotaldeliverystatus
        SourceFields:
        - OverallTotalDeliveryStatus
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        TaskType: Map
      - ConnectorOperator:
          S3: NO_OP
        DestinationField: overallsddocumentrejectionsts
        SourceFields:
        - OverallSDDocumentRejectionSts
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: character varying
        TaskType: Map