---
Resources:
  AFF3ADQC:
    Type: AWS::AppFlow::Flow
    Properties:
      FlowName: testZDMapAll1
      Description: ''
      TriggerConfig:
        TriggerType: OnDemand
      SourceFlowConfig:
        ConnectorType: Zendesk
        ConnectorProfileName: zd-amzn
        SourceConnectorProperties:
          Zendesk:
            Object: users
      DestinationFlowConfigList:
      - ConnectorType: S3
        DestinationConnectorProperties:
          S3:
            BucketName: samagrs-test-us-west-1
            S3OutputFormatConfig:
              FileType: CSV
              PrefixConfig:
                PrefixType: PATH
              AggregationConfig:
                AggregationType: SingleFile
      Tasks:
      - TaskType: Filter
        SourceFields:
        - id
        ConnectorOperator:
          Zendesk: PROJECTION
      - TaskType: Map
        SourceFields:
        - id
        TaskProperties:
        - Key: SOURCE_DATA_TYPE
          Value: integer
        - Key: DESTINATION_DATA_TYPE
          Value: integer
        DestinationField: UniqueId
        
        ConnectorOperator:
          Zendesk: NO_OP
      - TaskType: Map_all
        SourceFields: []
        TaskProperties:
        - Key: EXCLUDE_SOURCE_FIELDS_LIST
          Value: '["role"]'
        ConnectorOperator:
          Zendesk: NO_OP
      Tags:
      - Key: testKey
        Value: testValue
